/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import javax.swing.JOptionPane;
import modelo.Calculadora;

/**
 *
 * @author Anderson
 * @since 20/06/2017 - 16:36
 * @version 1.0 Beta Logan
 */
public class UICadCalculadora extends javax.swing.JFrame {

    Calculadora c=new Calculadora();
    /**
     * Creates new form UICadCalculadora
     */
    public UICadCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCalculos = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlNumero1 = new javax.swing.JLabel();
        jlNumero2 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtNumero1 = new javax.swing.JTextField();
        jtNumero2 = new javax.swing.JTextField();
        jrbSoma = new javax.swing.JRadioButton();
        jrbSubtrair = new javax.swing.JRadioButton();
        jrbMultiplicar = new javax.swing.JRadioButton();
        jrbDividir = new javax.swing.JRadioButton();
        jrbTodos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtResposta = new javax.swing.JTextArea();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlpDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jlNome.setText("Nome");

        jlNumero1.setText("Numero 1");

        jlNumero2.setText("Numero 2");

        bgCalculos.add(jrbSoma);
        jrbSoma.setText("Soma");
        jrbSoma.setActionCommand("soma");

        bgCalculos.add(jrbSubtrair);
        jrbSubtrair.setText("Subtrair");
        jrbSubtrair.setActionCommand("subtrair");

        bgCalculos.add(jrbMultiplicar);
        jrbMultiplicar.setText("Multiplicar");
        jrbMultiplicar.setActionCommand("multiplicar");

        bgCalculos.add(jrbDividir);
        jrbDividir.setText("Dividir");
        jrbDividir.setActionCommand("dividir");

        bgCalculos.add(jrbTodos);
        jrbTodos.setText("Todos");
        jrbTodos.setActionCommand("todos");

        jtResposta.setEditable(false);
        jtResposta.setColumns(20);
        jtResposta.setRows(5);
        jScrollPane1.setViewportView(jtResposta);

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNumero1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNumero2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNumero1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNumero2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbSoma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbSubtrair, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbMultiplicar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbDividir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbTodos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbTodos)
                    .addComponent(jrbDividir)
                    .addComponent(jrbMultiplicar)
                    .addComponent(jrbSubtrair)
                    .addComponent(jrbSoma)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jlpDadosLayout.createSequentialGroup()
                            .addComponent(jlNumero2)
                            .addGap(18, 18, 18)
                            .addComponent(jtNumero2))
                        .addGroup(jlpDadosLayout.createSequentialGroup()
                            .addComponent(jlNumero1)
                            .addGap(18, 18, 18)
                            .addComponent(jtNumero1))
                        .addGroup(jlpDadosLayout.createSequentialGroup()
                            .addComponent(jlNome)
                            .addGap(18, 18, 18)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumero1)
                    .addComponent(jtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumero2)
                    .addComponent(jtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jrbSoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSubtrair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMultiplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbDividir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbTodos)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jbCadastrar)
                .addGap(76, 76, 76)
                .addComponent(jbLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpDados)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados)
                .addGap(18, 18, 18)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        
        c.setNome(jtNome.getText());
        c.setNu1(Double.parseDouble(jtNumero1.getText()));
        c.setNu2(Double.parseDouble(jtNumero2.getText()));
        c.setOp(bgCalculos.getSelection().getActionCommand());
        
        
        JOptionPane.showMessageDialog(
                rootPane, 
                "Calculo cadastrado com sucesso! " + c.toString(), 
                "Relatorio", 
                JOptionPane.PLAIN_MESSAGE);
    }
    
    private void limpar(){
        jtNome.setText("");
        jtNumero1.setText("");
        jtNumero2.setText("");
        jtResposta.setText("");
        bgCalculos.clearSelection();
        
    }
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrar();
        
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCalculos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNumero1;
    private javax.swing.JLabel jlNumero2;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrbDividir;
    private javax.swing.JRadioButton jrbMultiplicar;
    private javax.swing.JRadioButton jrbSoma;
    private javax.swing.JRadioButton jrbSubtrair;
    private javax.swing.JRadioButton jrbTodos;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumero1;
    private javax.swing.JTextField jtNumero2;
    private javax.swing.JTextArea jtResposta;
    // End of variables declaration//GEN-END:variables
}
